omni-compiler/omni-compiler

- configure
- configure.in
We are using omni-compiler as a git submodule and building it directly from `cmake` with the `ExternalProject` definition. 
In this configuration, the `.git` directory is in fact a file and the `version` file generation will fail in that case. 
Changing the test resolve this problem and I think does not prevent the original behavior to work.
> Fix version file

- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-output-xcodeml.c
- F-FrontEnd/test/testdata/coarray_scalar_character.f90
This pull-request fixes the problem with the scalar character coarray like.
```fortran
program main
character(len=20) :: name[*]
end program main
```
> Bugfix for the scalar character coarray

- C-BackEnd/src/xcodeml/c/util/XmcXcodeToXcTranslator.java
- XcodeML-Exc-Tools/src/exc/xcodeml/XmcXobjectToXcodeTranslator.java
These commits support the code like below in C-BackEnd.
```c
#include <stdio.h>
void f(int aBc)
{
#pragma omp parallel num_threads(aBc)
{
int tnum = omp_get_thread_num();
printf("[%d]\n", tnum);
#pragma omp barrier
for (int i = 0; i < 10; i++)
printf("%d:%d\n", tnum, i);
}
}
int main () {
f(4);
return 0;
}
```
> Support the omp barrier directive & the omp num_threads clause in C decompiler

- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-compile-expr.c
- F-FrontEnd/src/F-compile.c
- F-FrontEnd/src/F-datatype.c
- F-FrontEnd/src/F-ident.c
- F-FrontEnd/test/testdata/type_bound_procedure_3.f90
- F-FrontEnd/test/testdata/type_bound_procedure_generic.f90
Fix bugs:
- fail if the type-bound procedure call appears before the procedure to bind appears
- fail if the type-bound generic call appears before the type-bound procedure is bound
And:
- add a warning for the DEFERRED type-bound procedure
- add a warning for the NON_OVRRIDEABLE type-bound procedure
> Fix bugs of the type-bound procedure

- F-FrontEnd/src/F-output-xcodeml.c
- F-FrontEnd/test/testdata/pointer_assignment_with_lower_bound.f90
This pull-request enable the pointer assignment to a subarray.
ex)
```fortran
p(1:,1:) => x
```
> Pointer assignment to a subarray

- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-compile-expr.c
- F-FrontEnd/src/F-compile.c
- F-FrontEnd/src/F-datatype.c
- F-FrontEnd/src/F-datatype.h
- F-FrontEnd/src/F-input-xmod.c
- F-FrontEnd/src/F-output-xcodeml.c
- F-FrontEnd/src/F95-parser.y
- F-FrontEnd/test/testdata/allocatable_character.f90
- F-FrontEnd/test/testdata/assign_to_allocatable_character.f90
- F-FrontEnd/test/testdata/assign_to_allocatable_integer_array.f90
- F-FrontEnd/test/testdata/procedure_declaration_in_block.f90
This pull-request enable the allocatable character,
ex)
```
CHARACTER(len=:), ALLOCATABLE :: c
```
and contains bugfix (missing the character length of the character which is imported from xmod)
> Allocatable character

- F-FrontEnd/src/F-compile.c
This pull request will fix the bug of the procedure variable imported from other module.
ex)
This code failed in the backend.
```fortran
module m
procedure, pointer(f) :: p
contains
function f(a)
end function f
end module m
program main
use m
end program main
```
> Fix bug of the procedure variable imported from other module

- F-FrontEnd/src/F-compile.c
- F-FrontEnd/test/testdata/coarray_syncimages.f90
This pull-request will fix the SYNC IMAGE to accept a one-rank integer array like:
```fortran
SYNC IMAGE((/1,2,3/))
```
> Accept the one-rank array for SYNC IMAGE

- F-BackEnd/src/xcodeml/f/decompile/XfDecompileDomVisitor.java
- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-compile-expr.c
- F-FrontEnd/src/F-compile.c
- F-FrontEnd/test/failtestdata/derived_type_and_override_private_member.f90
- F-FrontEnd/test/testdata/derived_type_private_and_public.f90
- F-FrontEnd/test/testdata/derived_type_private_for_submodule.f90
- F-FrontEnd/test/testdata/derived_type_private_member.f90
This pull-request will fix the bug of public/private in the derived-type declaration.
The previous build remove the public attribute of members of the derived-type.
```fortran
TYPE t
PRIVATE
INTEGER :: v
INTEGER,PUBLIC :: u
END TYPE t
```
This code was translated like:
```fortran
TYPE t
PRIVATE
INTEGER :: v
INTEGER :: u
END TYPE t
```
So this pull-request will output the public attribute if the member has it.
> Fix for public/private in the derived-type declaration

- F-FrontEnd/src/F-datatype.c
This pull requet will fix the bug of the procedure pointer assignment.
ex)
```fortran
INTERFACE
FUNCTION f(a)
INTEGER :: f ,a
END FUNCTION f
FUNCTION g(b)
INTEGER :: g, b
END FUNCTION g
END INTERFACE
PROCEDURE(f), POINTER :: p
p => g ! failed here
```
The previous build fail at the pointer assignment to the procedure pointer.
It is because that the argument name is different between `f` and `g`.
But actually the above code is valid.
> Fix bug of the procedure pointer assignment

- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-compile-expr.c
- F-FrontEnd/src/F-output-xcodeml.c
- F-FrontEnd/test/failtestdata/parameterized_type_invalid_type_parameter.f90
- F-FrontEnd/test/failtestdata/parameterized_type_invalid_type_parameter_2.f90
This pull request will add checking for the type paramter.
The follwing codes should be invalid:
```fortran
TYPE t (l)
INTEGER, KIND :: k = kind(4) ! not exists in type parameters
INTEGER, LEN :: l = 10
INTEGER, LEN :: l = 12 ! duplicate
INTEGER(KIND=k) :: v
END TYPE t
```
> Add checking to the type parameter

- configure
- configure.in
Since version 8.5, the Cray compiler is printing version information on the stderr instead of stdout. Therefore, the configure script will failed with this configuration. 
This PR will enable OMNI to be compiled with the Cray Compiler 8.5
```bash
CC=cc FC=ftn ./configure --target=Cray-linux-gnu MPI_CC=cc MPI_FC=ftn
```
> Support Cray Compiler 8.5

- F-BackEnd/src/xcodeml/f/decompile/XfDecompileDomVisitor.java
- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-compile.c
- F-FrontEnd/src/F-front.h
- F-FrontEnd/src/F95-lex.c
- F-FrontEnd/src/F95-parser.y
- F-FrontEnd/test/failtestdata/select_type_duplicate_class_default.f90
- F-FrontEnd/test/failtestdata/select_type_duplicate_primitive_types.f90
- F-FrontEnd/test/testdata/select_type.f90
- F-FrontEnd/test/testdata/select_type_with_primitive_types.f90
This pull request has following improvments for the select type construct:
- accepts intrinsic types in TYPE IS/ CLASS IS statement
```fortran
SELECT TYPE (p)
TYPE IS (INTEGER(KIND=4))
TYPE IS (INTEGER(KIND=8))
END SELECT TYPE
```
- changes a type of selector inside a type guard clause
```fortran
SELECT TYPE (p)
TYPE IS (t)
WRITE(*,*) p%member
TYPE IS (subtype_of_t)
WRITE(*,*) p%member_of_sub_type
END SELECT TYPE
```
- checks types in TYPE IS / CLASS IS statement
```fortran
SELECT TYPE (p)
TYPE IS (INTEGER)
TYPE IS (INTEGER) ! this statement will cause error
END SELECT TYPE
```
> Improve the select type construct

- F-FrontEnd/src/F-compile-expr.c
- F-FrontEnd/test/testdata/type_constractor_skip_allocatable_member.f90
This pull-request will skip the derived-type member initialization if it is allocatable
ex)
```fortran
TYPE t
INTEGER :: v
INTEGER, ALLOCATABLE, DIMENSION(:) :: w
END TYPE t
TYPE(t) :: a = t(v=1) ! skip initialization of member 'w'
```
> Skip initialization of allocatable member 

- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-compile-expr.c
- F-FrontEnd/test/failtestdata/function_result_ponter_without_declared_function.f90
- F-FrontEnd/test/testdata/function_result_pointer_1.f90
- F-FrontEnd/test/testdata/function_result_pointer_2.f90
This pull-request will implement for the assignment to the result of the pointer function.
ex)
```
module mod
real,target :: tmp
contains
function f(key) result(res)
real,intent(in) :: key
real,pointer :: res
tmp = key + 2.0
res => tmp
end function f
end module mod
!
program main
use mod
real a
a = 3.0
print *, f(a)
f(a) = 6.0   ! Assignment to the result of the pointer function
print *, f(a)
end program main
```
> Assignment to the result of the pointer function

- XcodeML-Exc-Tools/src/exc/xcalablemp/XMPtranslateLocalPragma.java
- libxmp/src/xmp_async.c
- libxmp/src/xmp_barrier.c
- libxmp/src/xmp_bcast.c
- libxmp/src/xmp_coarray.c
- libxmp/src/xmp_reduce.c
- libxmp/src/xmp_reflect.c
- libxmp/src/xmpc_gmove.c
- libxmp/src/xmpc_task.c
The runtime/compiler generated code needs to provide storage of type xmpt_tool_data_t. 
The begin callback hands over the address to allow the tool to modify the value.
For symetry also the end callback provides the address.
> Enable the XMPT tool to store data in the data object

- F-FrontEnd/src/F95-lex.c
#192 
I think the Hollerith constant detection should even be removed from the lexer as it has been removed from the Fortran 95 standard.
> Fix detection of hollerith code. Fix for issue #192

- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-compile.c
- F-FrontEnd/src/F-ident.h
- F-FrontEnd/src/F-output-xcodeml.c
- F-FrontEnd/test/testdata/submodule_3.f90
This pull-request will fix the visibility in the INTERFACE construct.
From INTERFACE construct, identifiers in the outer scope shold not be visibile without IMPORT statement。.
> Fix visibility in INTERFACE construct

- F-BackEnd/src/xcodeml/f/decompile/XfDecompileDomVisitor.java
- F-FrontEnd/src/F-compile.c
- F-FrontEnd/src/F-output-xcodeml.c
- F-FrontEnd/test/testdata/complex_member_ref.f08
This pull request will implement referencing the part of complex value
```fortran
COMPLEX :: a
a%RE = 1.0
a%IM = 2.0
```
> reference the part of complex value

- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-output-xcodeml.c
- F-FrontEnd/src/F95-parser.y
- F-FrontEnd/test/testdata/issue314.f90
>  Fix syntax error for type-bound GENERIC statement with access-spec (Fix #314)

- F-FrontEnd/src/F-compile.c
- F-FrontEnd/src/F-datatype.h
- F-FrontEnd/test/testdata/issue316.f90
>  Allow to be marked as private/public if access-spec of type was inferred (Fix #316)

- F-FrontEnd/src/F-intrinsic.c
- F-FrontEnd/src/F-intrinsics-table.c
- F-FrontEnd/test/testdata/intrinsic_max.f90
- F-FrontEnd/test/testdata/intrinsic_maxloc.f90
- F-FrontEnd/test/testdata/intrinsic_maxloc_2.f90
- F-FrontEnd/test/testdata/intrinsic_maxloc_3.f90
- F-FrontEnd/test/testdata/intrinsic_min.f90
This pull request will make the follwing intrinsic procedure accept CHARACTER (scala or array) as a argument:
- MAX
- MIN
- MAXLOC
- MINLOC
And fix the retrun type of MAXLOC/MINLOC.
> improve arguments of intrinsic procedures

- F-FrontEnd/src/F-intrinsics-table.c
> Use INTR_TYPE_NONE for empty list (Fix #333)

- F-FrontEnd/src/F-compile-expr.c
- F-FrontEnd/test/testdata/_issue319.f90
- F-FrontEnd/test/testdata/issue319.f90
> Recover correct return type for external type bound procedure call (Fix #319)

- F-FrontEnd/src/F-compile-expr.c
- F-FrontEnd/src/F-compile.c
- F-FrontEnd/src/F-output-xcodeml.c
- F-FrontEnd/test/testdata/type_parameter_inquiry_1.f90
- F-FrontEnd/test/testdata/type_parameter_inquiry_2.f90
This pull request will implement type parameter inquiry for primitive types.
ex)
```fortran
PRINT *, i%KIND, c%LEN
```
The type parameter inquiry `KIND` and `LEN` will be transformed into an intrinsic function call.
The above code will be translated like:
```fortran
PRINT *, KIND(i), LEN(c)
```
> Type Parameter Inquiry

- F-FrontEnd/src/F-compile-decl.c
- F-FrontEnd/src/F-datatype.c
- F-FrontEnd/src/F-front.h
- F-FrontEnd/test/testdata/implicit_shape.f08
This pull request implement implicit shape.
ex)
```fortran
INTEGER, PARAMETER, DIMENSION(1:*, *) :: array = RESHAPE((/1,2,3,4,5,6/), (/2,3/))
```
> Implied shape

- F-FrontEnd/src/F95-parser.y
- F-FrontEnd/test/testdata/primitive_type_with_type_spec.f90
This pull request will accept `TYPE(primitive type)`
ex)
```fortran
TYPE(INTEGER) :: i
TYPE(REAL)    :: r
TYPE(CHARACTER(LEN=8)) :: c
```
> Accept TYPE(primitive type)

- F-FrontEnd/src/F-compile.c
- F-FrontEnd/src/F95-parser.y
This pull request will fix regressions caused by belows:
- 070c429
- fail with tests/xcalablemp/others/F/procedure_declaration_5.F90
- 1fd00c7
- fail with F-FrontEnd/test/testdata/function_with_prefixes.f90
> Fix some regressions

- F-FrontEnd/src/F-datatype.h
This pull request will fix the merge conflict caused by 6c50863d9dbf90f2ddc4ffd70fd06ccf52c7479c
Fix:
- Duplicate IS_PROCEDURE_POINTER macros
> Fix merge conflict

- F-FrontEnd/src/F-compile.c
- F-FrontEnd/src/F-output-xcodeml.c
- F-FrontEnd/test/testdata/issue559.f90
#559 
@h-murai @shingo-s The problem seems to come from `VAR_INIT_VALUE` being defined somehow for the `FINAL` subroutine `ID`. This then leads to a segfault in `outx_varDecl` as it is wrongly define and make no sense. 
I didn't find where this value is set actually. So I did a quick fix in `check_final_subroutines`. If you have any idea where this might come from, I'll gladly change this fix.
> Fix #559: Do not output varDecl for tbp related ids

- F-FrontEnd/src/F-compile.c
- F-FrontEnd/test/testdata/issue550.f90
Fix #550 
The type is redefined in the `CLASS IS` block but I think we need to keep the attributes information as they are needed sometimes.
> Fix #550: Keep type attribute in CLASS IS block

- libxmp/include/xmp.h
- libxmp/include/xmp_data_struct.h
- libxmp/include/xmp_func_decl.h
- libxmp/include/xmp_internal.h
- libxmp/include/xmpt.h
- libxmp/src/xmp_align.c
- libxmp/src/xmp_async.c
- libxmp/src/xmp_nodes.c
- libxmp/src/xmp_runtime.c
- libxmp/src/xmp_template.c
- libxmp/src/xmpt_lib.c
- libxmpf/include/xmpf_internal.h
- libxmpf/src/Makefile.in
- libxmpf/src/xmpf_async.c
- New functions `xmpt_desc_get_data(xmp_desc_t, xmpt_tool_data_t*)` and `xmpt_desc_set_data(xmp_desc_t, xmpt_tool_data_t)` to set and get data from a descriptor. The field is initially NULL.
- xmp.h and xmpt.h can now be included in C++ code (xmp-functions have extern "C" in that case)
- The function xmpt_initialize is only called once per tool, following the algorithm for omp_start_tool in TR6
- Fix the descriptor provided in the wait_async event
> Serveral additions for XMPT
