omni-compiler/omni-compiler

F-FrontEnd/src/F-compile.c
F-FrontEnd/src/F-input-xmod.c
F-FrontEnd/test/testdata/__private_member.f90
F-FrontEnd/test/testdata/end_statement_for_module_with_contains.f90
F-FrontEnd/test/testdata/end_statements.f90
F-FrontEnd/test/testdata/use_private_member_from_submodule.f90

This pull request will fix the issues #78 and #79 This pull request will fix the issues #78 and #79

Fix #78 and #79

---

F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/src/F-compile.c
F-FrontEnd/src/F-datatype.h
F-FrontEnd/src/F-front.h
F-FrontEnd/test/failtestdata/too_long_array.f90
F-FrontEnd/test/testdata/long_array_1.f90
F-FrontEnd/test/testdata/long_array_2.f90

This pull requets extend the array dimension from 7 to 15 (rank + corank).

Extend the array dimension

---

F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/src/F-compile-expr.c
F-FrontEnd/src/F-compile.c
F-FrontEnd/src/F-output-xcodeml.c
F-FrontEnd/test/testdata/procedure_declaration_6.f90
F-FrontEnd/test/testdata/procedure_declaration_backward_reference_1.f90
F-FrontEnd/test/testdata/procedure_declaration_refer_procedure_variable.f90

This pull request fixes the bugs caused by the procedure declaration implementation

Fix bugs of the procedure declaration implementation

---

F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/src/F-compile-expr.c
F-FrontEnd/src/F-output-xcodeml.c
F-FrontEnd/test/testdata/_issue108_mod.f90
F-FrontEnd/test/testdata/issue108.f90
F-FrontEnd/test/testdata/issue108_prog.f90

Fix segmentation fault with kind parameter definition

---

F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/src/F-compile.c
F-FrontEnd/src/F-output-xcodeml.c
F-FrontEnd/test/testdata/interface_with_public_attr.f90

This pull request will fix #113

Bugfix for 113

---

configure
configure.in

The fix #136 breaks the compatibility with the Cray Compiler >=8.5. This will make it works again.

Fix Cray 8.5 configure

---

F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/test/testdata/character_length_plus_expr.f90

Fix for #138

---

F-FrontEnd/src/F-ident.h

This pull request will fix 6bb92e, reverting some changes

Fix 6bb92e, revert some changes

---

F-BackEnd/bin/F_Back.in

This pull request will fix F_Back problem which was caused by renaming a jar file

Fix F_Back for renaming a jar file

---

F-BackEnd/src/xcodeml/f/decompile/XfDecompileDomVisitor.java
F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/src/F-compile.c
F-FrontEnd/src/F-datatype.c
F-FrontEnd/src/F-intrinsic.c
F-FrontEnd/src/F-output-xcodeml.c
F-FrontEnd/test/testdata/intrinsic_attribute_1.f90
F-FrontEnd/test/testdata/intrinsic_attribute_2.f90
F-FrontEnd/test/testdata/intrinsic_statement_for_gnu_intrinsic.f90

This pull-request will fix #128 and it modify INTRINSIC statement and attribute.

Bugfix for #128

---

F-FrontEnd/src/F-compile-expr.c
F-FrontEnd/test/testdata/issue208.f90

Do not return struct constructor in assignment (Fix for #208)

---

F-FrontEnd/src/F95-parser.y
F-FrontEnd/test/testdata/iso_c_binding.f90

Fix function suffix grammar. Fix issue #214

---

F-BackEnd/src/xcodeml/f/decompile/XfDecompileDomVisitor.java
F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/src/F95-parser.y
F-FrontEnd/test/testdata/iso_c_binding2.f90

Allow BIND name in declaration (Fix for #issue228)

---

F-FrontEnd/src/F-compile.c
F-FrontEnd/src/F95-parser.y
F-FrontEnd/test/testdata/if_where.f90

Accept where as an action-stmt for IF (issue #205)

---

F-BackEnd/src/xcodeml/f/decompile/XfTypeManagerForDom.java
F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/src/F-compile.c
F-FrontEnd/test/testdata/procedure_declaration_8.f90
F-FrontEnd/test/testdata/procedure_declaration_with_bind.f90

This pull request will fix #247 and accpet a procedure declaration statement with a bind attribute

Fix #247 and accpet a procedure declaration statement with a bind attribute

---

F-FrontEnd/src/F95-lex.c
F-FrontEnd/test/testdata/issue253.f90

Do not consider ! in string constant when looking for continuation char (Fix #253)

---

F-BackEnd/src/xcodeml/f/decompile/XfDecompileDomVisitor.java
F-FrontEnd/test/testdata/public_and_private_over_modules.f90
XcodeML-Exc-Tools/src/xcodeml/util/XmDomUtil.java

This pull reuqest applies f64b5351 again and fixes the build error caused by the merge

Fix build error

---

F-FrontEnd/src/F-compile-expr.c
F-FrontEnd/test/testdata/issue207.f90

Keep the correct type of the operand (Fix for issue 207)

---

F-BackEnd/src/xcodeml/f/decompile/XfDecompileDomVisitor.java
F-FrontEnd/src/F-input-xmod.c
F-FrontEnd/src/F-output-xcodeml.c
F-FrontEnd/test/testdata/issue276.f90

Produce and read <symbols> node in FfunctionDecl

---

F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/test/testdata/issue279.f90

Fix #279 
@h-murai @shingo-s Is there a way to do a full test (test data -> F_Front -> XML -> F_Back)?

Do not set non-function type to function (Fix #279)

---

F-FrontEnd/src/F-output-xcodeml.c
F-FrontEnd/test/testdata/_issue282.f90
F-FrontEnd/test/testdata/_issue282_mod.f90
F-FrontEnd/test/testdata/issue282.f90

Keep kind specifier for constant var (Fix #282)

---

F-FrontEnd/src/F95-parser.y
F-FrontEnd/test/testdata/issue306.f90

 Accept len=: and len=* after kind= for character decl (Fix #306)

---

F-FrontEnd/src/F-compile.c
F-FrontEnd/test/testdata/issue302.f90

Fix for issue #302

---

F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/test/testdata/issue326.f90

 Accept GENERIC tbp binding on multiple statement (Fix #326)

---

F-FrontEnd/src/F-intrinsic.c
F-FrontEnd/test/testdata/issue328.f90

Fix check of intrinsic argument for array reference with TARGET (Fix #328)

---

F-BackEnd/src/xcodeml/f/decompile/XfDecompileDomVisitor.java
F-FrontEnd/src/F-compile.c
F-FrontEnd/src/F-output-xcodeml.c
F-FrontEnd/src/F95-lex.c
F-FrontEnd/src/F95-parser.y
F-FrontEnd/test/testdata/_issue321.f90
F-FrontEnd/test/testdata/issue321.f90

Accept assignment(=) and operator() in USE-ONLY statement (Fix #321)

---

F-FrontEnd/src/F-compile-decl.c
F-FrontEnd/src/F-compile-expr.c
F-FrontEnd/src/F-varutil.c
F-FrontEnd/test/testdata/character_length_plus_expr_implicitly.f90
F-FrontEnd/test/testdata/procedure_pointer_assign_with_character_length.f90

This pull request will fix #364

Revert "Revert "Merge branch 'bugfix/364'""

---

F-FrontEnd/src/F-compile-expr.c
F-FrontEnd/src/F-front.h
F-FrontEnd/src/F-varutil.c
F-FrontEnd/test/testdata/_issue492.f90
F-FrontEnd/test/testdata/issue492.f90

Fix issue #492

---

F-FrontEnd/src/F-compile-expr.c
F-FrontEnd/src/F-datatype.c
F-FrontEnd/src/F-front.h
F-FrontEnd/test/testdata/array_constractor_with_type_3.f90

Reverts omni-compiler/omni-compiler#521

Revert "Fix #505"

---

F-FrontEnd/src/F-compile-expr.c
F-FrontEnd/test/testdata/issue566.f90

Fix #566: Return correct id/type when multi

---

XcodeML-Exc-Tools/src/exc/util/omompx.java
XcodeML-Exc-Tools/src/exc/xmpF/XMPenv.java
XcodeML-Exc-Tools/src/exc/xmpF/XMPotype.java
XcodeML-Exc-Tools/src/exc/xmpF/XMPtranslate.java
XcodeML-Exc-Tools/src/exc/xmpF/XMPtypecheckStencilKernel.java

I implemented type checking for stencil kernels. The type system is elaborated in my MPLR2019 paper.
Tatsuya Abe
A Type System for Data Independence of Loop Iterations in a Directive-Based PGAS Language
In Proceedings of the 16th International Conference on Managed Programming Languages and Runtimes (MPLR), pages 50--62, 2019.
doi: 10.1145/3357390.3361021

implement type checking for stencil kernels
